# training template for your executor app
# after build image, it should at /img-man/training-template.yaml
# key: gpu_id, task_id, pretrained_model_params, class_names should be preserved

# gpu_id: '0'
# task_id: 'default-training-task'
# pretrained_model_params: []
# class_names: []

batch_size: 2
num_workers: 2
epochs: 50
learning_rate: 0.0001
eval_size: 640
backbone_name: 'swin_nano'
weight_save_interval: 100
args_options: ''
